#!/bin/bash
# idx-searching index-file [keys...]
# Look up keys in an index; print the docids they're all in, one per line.

idx=$1; shift

if [ 1 == $# ]; then
	tar xf $idx --to-stdout keys/$1 2>/dev/null
elif [ 1 '<' $# ]; then
	key=$1; shift
	comm -12 <(tar xf $idx --to-stdout keys/$key 2>/dev/null) \
                 <(idx-searching $idx "$@")
fi
